### ISSUE TITLE
handle relative paths in datasource files

### ISSUE THREAD

**Issue by bdon** [mojodna/tilelive-tmsource#2]
```
TypeError: Parameter 'url' must be a string, not undefined
at Url.parse (url.js:107:11)
at Object.urlParse [as parse] (url.js:101:5)
```

when we have a datasource such as:

```
- id: ne_110m_land
Datasource: 
  file: data/ne_110m/ne_110m_land.shp
  type: shape
description: ''
fields: 
  featurecla: String
  scalerank: Number
properties: 
  "buffer-size": 8
srs: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs
```
